xdg-open https://extensions.gnome.org/extension/1460/vitals/
xdg-open https://extensions.gnome.org/extension/4290/disable-workspace-switch-animation-for-gnome-40/
xdg-open https://extensions.gnome.org/extension/4356/top-bar-organizer/
xdg-open https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/
xdg-open https://extensions.gnome.org/extension/4451/logo-menu/
xdg-open https://extensions.gnome.org/extension/4627/focus-changer/
xdg-open https://extensions.gnome.org/extension/5090/space-bar/
xdg-open https://extensions.gnome.org/extension/744/hide-activities-button/
xdg-open https://extensions.gnome.org/extension/4688/focus-follows-workspace/
